### ISSUE TITLE
Which library to use for using webGL library API

### ISSUE THREAD

**Issue by rahuldess** [rahuldess/influx#1]

**Comment by shaunshapiro** [comment]
three.js seems to have lots of support. Other libraries seem to be good for specialized applications such as games etc. but for our purposes three might be best.

**Comment by umliuxin** [comment]
Do we decide to use three.js?

**Comment by rahuldess** [comment]
@umliuxin i havent got chance to look at it ..add your inputs also ..ill add mine by end of weekend

**Comment by umliuxin** [comment]
I check on google. It looks like there are two popular webGL wireframe
- three.js
- babylon.js

I am reading some articles about the comparison between them. It looks like three.js is a better fit for our project.

> While Three.js was designed as a tool for general purpose web animations, Babylon.js was designed to take a more targeted approach for web-based game development and uses an extensive physics engine for collision detection and other intricacies involved for 3D graphics.

For reference

http://www.html5gamedevs.com/topic/12789-choose-between-threejs-and-babylonjs/
http://www.3pillarglobal.com/insights/3d-graphics-with-webgl-three-js-babylon-js
http://www.sitepoint.com/three-js-babylon-js-comparison-webgl-frameworks/

**Comment by rahuldess** [comment]
thats good ..lets go with `three.js` then ..i dint get chance to look into it but lets go with it as you both have looked into it.
